import "./table.css";

function planets() {
    return (
        <div className="p-7">
            <h1 className="planet">The Mercury</h1>
            <br />
            <p>Mercury is the innermost and smallest planet in the Solar System, with a diameter of about 4,880 kilometres (3,032 miles), slightly larger than Earth's Moon. Named after the Roman god of commerce, its swift movement across the sky led to its designation as a messenger deity. Its proximity to the Sun makes it challenging to observe without telescopes.</p>
            <br />
            <p>The surface is heavily cratered and resembles the Moon, featuring vast plains and large craters like Caloris Planitia, about 1,550 kilometres (960 miles) wide. Mercury has a solid silicate crust over a metallic core that constitutes about 75% of its volume, resulting in a high density of approximately 5.427 g/cm³.</p>
            <br />
            <p>Internally, Mercury consists of a silicate mantle and a primarily iron core, possibly containing nickel and sulfur. A massive impact in its early history may have stripped away much of its original mantle, supported by data from the MESSENGER spacecraft.</p>
            <br />
            <p>The planet's surface shows numerous impact craters due to collisions over billions of years, with temperature variations ranging from 427 °C (800 °F) during the day to -173 °C (-280 °F) at night. Mercury has an extremely thin exosphere composed of atoms released from its surface by solar radiation and micrometeoroid impacts, containing elements like oxygen (42%) and sodium (29%).</p>
            <br />
            <p>Mercury's weak magnetic field is about 1% stronger than Earth's and is generated by molten iron motion in its outer core. This magnetic field varies significantly across regions and is stronger in the northern hemisphere.</p>
            <br />
            <p>Exploration has been limited due to its harsh environment. The MESSENGER spacecraft provided valuable data from 2004 to 2015, revealing insights into Mercury’s geology and atmosphere. BepiColombo is en route to Mercury, aiming to arrive in 2025 to investigate its mysteries and formation theories further.</p>

            <br />

            <h1 className="planet">The Venus</h1>
            <br />
            <p>
                Venus, the second planet from the Sun, is often called Earth's "sister planet" due to its similar size of about 12,104 kilometres (7,521 miles). It is the third brightest object in the sky but has extreme atmospheric conditions that create a hostile environment for life.
            </p>
            <br />
            <p>
                With a dense atmosphere of 96% carbon dioxide and 3% nitrogen, Venus experiences a powerful greenhouse effect, leading to surface temperatures of up to 465 °C (869 °F) and an atmospheric pressure of about 95 times Earth's. The surface features volcanic landscapes and extensive plains obscured by thick sulfuric acid clouds.
            </p>
            <br />
            <p>
                The atmosphere consists of distinct layers: a lower atmosphere rich in sulfuric acid, a middle stratosphere, and an upper atmosphere. High winds can reach up to 360 kilometres per hour (224 mph).
            </p>
            <br />
            <p>
                Exploration has included missions like NASA's Magellan and the Soviet Venera probes. Recent studies suggest possible ongoing volcanic activity. Some scientists speculate about microbial life in the upper atmosphere, where temperatures are more moderate, and unusual streaks in the clouds may indicate biological activity or unknown processes.
            </p>

            <br />

            <h1 className="planet">The Earth</h1>
            <br />
            <p>
                Earth is the third planet from the Sun and the only known astronomical object to support life. Formed about 4.5 billion years ago, it has solid land, liquid water, and a dynamic atmosphere that fosters diverse ecosystems. Oceans cover roughly 71% of its surface, regulating temperature and creating distinct seasons.
            </p>
            <br />
            <p>
                Earth is the fifth-largest planet in the Solar System, with a diameter of about 12,742 kilometres (7,918 miles). Its oblate spheroid shape is slightly flattened at the poles and bulging at the equator. The atmosphere, composed mainly of nitrogen (78%) and oxygen (21%), protects against solar radiation and regulates temperature through greenhouse gases.
            </p>
            <br />
            <p>
                Water is essential for life, with 97% found in oceans and only 3% in freshwater. The water cycle ensures continuous recycling of water. Earth hosts millions of species across various habitats, making biodiversity crucial for ecosystem resilience, though human activities threaten it.
            </p>
            <br />
            <p>
                The Earth's interior consists of layers: inner core (solid), outer core (liquid), mantle (semi-solid), and crust (solid). Tectonic plate movement causes geological phenomena like earthquakes and volcanic eruptions.
            </p>
            <br />
            <p>
                Human impact has significantly increased greenhouse gas emissions, contributing to climate change. Sustainable practices are vital for mitigating these effects and ensuring a healthy planet for future generations.
            </p>

            <br />

            <h1 className="planet">The Mars</h1>
            <br />
            <p>
                Mars, the fourth planet from the Sun, is known as the "Red Planet" due to its iron oxide surface. It is about 228 million kilometres (142 million miles) from the Sun and has a diameter of approximately 6,779 kilometres (4,212 miles). A day on Mars lasts about 24 hours and 37 minutes, while a year is around 687 Earth days. Mars has two small moons, Phobos and Deimos, believed to be captured asteroids.
            </p>
            <br />
            <p>
                The planet features Olympus Mons, the largest volcano in the Solar System at 21.9 kilometres (13.6 miles), and Valles Marineris, a canyon system over 4,000 kilometres (2,500 miles) long. Its thin atmosphere is mostly carbon dioxide (95%), resulting in less than 1% of Earth's surface pressures.
            </p>
            <br />
            <p>
                Mars experiences temperature fluctuations, averaging around -63 °C (-81 °F), with extremes from -125 °C (-195 °F) at the poles to about 20 °C (68 °F) at the equator. It has seasons due to its axial tilt and experiences massive dust storms.
            </p>
            <br />
            <p>
                Evidence suggests Mars once had liquid water, with ancient river valleys indicating a wetter climate. Current studies show subsurface ice deposits and possible intermittent liquid water flow.
            </p>
            <br />
            <p>
                Phobos and Deimos have irregularly shaped moons, with Phobos spiralling inward and expected to collide with Mars or break apart in about 50 million years.
            </p>
            <br />
            <p>
                Mars has been explored since the mid-20th century through missions like NASA's Viking landers and rovers such as Curiosity and Perseverance, significantly enhancing our understanding of its geology and potential for life.
            </p>

            <br />

            <h1 className="planet">Jupiter</h1>
            <br />
            <p>
                Jupiter is the fifth planet from the Sun and the largest in the Solar System, with a mass over 2.5 times
                that of all other planets combined. Its diameter is about 139,822 kilometres (86,881 miles), primarily
                composed of hydrogen and helium. Jupiter's strong gravitational pull influences nearby asteroids and
                comets, acting as a protective "sweeper" for inner planets.
            </p>
            <br />
            <p>
                The planet rotates rapidly, completing a rotation in about 10 hours, resulting in an oblate spheroid
                shape. Its atmosphere features colourful clouds and the Great Red Spot, a massive storm larger than Earth.
                Composed mainly of hydrogen (90%) and helium (10%), the atmosphere experiences high-speed winds reaching
                up to 360 kilometres per hour (224 mph).
            </p>
            <br />
            <p>
                Jupiter has the strongest magnetic field of any planet, creating a vast magnetosphere that captures solar
                wind particles and produces spectacular auroras. It has 95 recognised moons, including the four
                largest—Io, Europa, Ganymede, and Callisto—each with unique geological features.
            </p>
            <br />
            <p>
                Exploration began in the 1970s with Pioneer missions, followed by Voyager missions that provided detailed
                data. NASA's Juno spacecraft currently studies Jupiter's atmosphere and magnetic field, while upcoming
                missions like Europa Clipper aim to investigate Europa's potential for life.
            </p>

            <br />

            <h1 className="planet">Saturn</h1>
            <br />
            <p>
                Saturn is the sixth planet from the Sun and the second-largest in the Solar System, known for its stunning
                ring system. It primarily comprises hydrogen and helium, with a diameter of about 120,536 kilometres
                (74,898 miles) and a mass approximately 95 times that of Earth. Saturn takes about 29.5 Earth years to orbit
                the Sun, while a day lasts around 10.7 hours due to its rapid rotation.
            </p>
            <br />
            <p>
                The atmosphere consists mainly of hydrogen (96%) and helium (3%), with trace gases like methane and ammonia
                contributing to its pale yellow hue. High-speed winds can reach up to 1,800 kilometres per hour
                (1,100 miles per hour), creating complex weather patterns.
            </p>
            <br />
            <p>
                Saturn's ring system is one of the most remarkable features in the Solar System, composed mainly of ice
                particles that range from tiny grains to large chunks. The rings extend up to 282,000 kilometres
                (175,000 miles) from the planet but are incredibly thin—often less than 1 kilometre (0.6 miles) thick.
            </p>
            <br />
            <p>
                Saturn has over 146 recognised moons, with Titan being the largest and notable for its dense nitrogen-rich
                atmosphere and surface lakes of liquid methane. Other significant moons include Enceladus, which has geysers
                indicating a subsurface ocean.
            </p>
            <br />
            <p>
                Saturn has been explored by several spacecraft, starting with Pioneer 11 in 1979, followed by Voyager
                missions. NASA's Cassini spacecraft provided the most comprehensive exploration, orbiting Saturn from
                2004 to 2017 and revealing intricate details about its rings and moons.
            </p>

            <br />

            <h1 className="planet">Uranus</h1>
            <br />
            <p>
                Uranus is the seventh planet from the Sun and an ice giant known for its blue-green colour. Discovered in
                1781 by William Herschel, it has a diameter of about 50,724 kilometres (31,518 miles) and a mass
                approximately 14.5 times that of Earth. Uranus orbits the Sun at an average distance of about 2.87 billion
                kilometres (1.78 billion miles), taking around 84 Earth years to complete one orbit.
            </p>
            <br />
            <p>
                The planet's internal structure consists mainly of water, ammonia, and methane, while its atmosphere is
                primarily hydrogen (83%) and helium (15%), with methane contributing to its colour. Uranus has a low mean
                density of about 1.27 g/cm³ and an axial tilt of about 82 degrees, causing it to rotate almost on its side.
            </p>
            <br />
            <p>
                Uranus has strong winds reaching up to 900 kilometres per hour (560 miles per hour) and the lowest recorded
                temperature in the Solar System at around -224 °C (-371 °F). Its ring system is faint but consists of at
                least 13 narrow rings made of boulder-sized particles.
            </p>
            <br />
            <p>
                Uranus has at least 28 known moons, including the five largest—Miranda, Ariel, Umbriel, Titania, and Oberon—
                each displaying diverse geological activity and evidence of past tectonic processes.
            </p>
            <br />
            <p>
                Uranus has only been visited once by NASA's Voyager 2 spacecraft in 1986. Further exploration is planned
                to understand the planet's composition, atmosphere, and potential moons in more detail.
            </p>

            <br />

            <h1 className="planet">Neptune</h1>
            <br />
            <p>
                Neptune is the eighth and farthest planet from the Sun, known for its vibrant blue colour. Discovered in
                1846 by Johann Galle, its diameter is about 49,244 kilometres (30,598 miles), and its mass is approximately
                17 times that of Earth. Neptune orbits the Sun at a distance of about 4.5 billion kilometres
                (2.8 billion miles), taking nearly 165 Earth years to complete one orbit.
            </p>
            <br />
            <p>
                Neptune's atmosphere consists primarily of hydrogen (80%), helium (19%), and methane (1.5%), with high-speed
                winds reaching up to 2,100 kilometres per hour (1,300 miles per hour), the fastest in the Solar System.
                Methane absorbs red light, giving the planet its deep blue hue.
            </p>
            <br />
            <p>
                Like Uranus, Neptune has a faint ring system made of dark, narrow rings and arcs. The planet's dynamic
                atmosphere exhibits massive storms, including the Great Dark Spot, similar to Jupiter's Great Red Spot.
            </p>
            <br />
            <p>
                Neptune has at least 14 moons, with Triton being the largest and geologically active, featuring geysers that
                erupt nitrogen gas. Triton is the only large moon in the Solar System with a retrograde orbit, suggesting it
                may have been captured from the Kuiper Belt.
            </p>
            <br />
            <p>
                Neptune was visited once by NASA's Voyager 2 spacecraft in 1989, which provided detailed data on its
                atmosphere, rings, and moons.
            </p>
        </div>
    )
}

export default planets;